Debuging bump version pipeline

diff --git a/.github/workflows/bump-version.yml b/.github/workflows/bump-version.yml
--- a/.github/workflows/bump-version.yml
+++ b/.github/workflows/bump-version.yml
@@ -37,23 +37,30 @@ jobs:
           git fetch origin main --depth=2
 
           # Get list of changed files between last commit and one before
-          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
+          CHANGED_FILES=$(git diff --name-only origin/main~1..origin/main)
           echo "Changed files: $CHANGED_FILES"
 
           HAS_FRONTEND_CHANGES=false
           HAS_BACKEND_CHANGES=false
+          HAS_INFRA_CHANGES=false
 
           for file in $CHANGED_FILES; do
             if [[ $file == frontend/* ]]; then
               HAS_FRONTEND_CHANGES=true
-            else
+            elif [[ $file == backend/* ]]; then
               HAS_BACKEND_CHANGES=true
+            else
+              HAS_INFRA_CHANGES=true
             fi
           done
 
           echo "Frontend changes: $HAS_FRONTEND_CHANGES"
           echo "Backend changes: $HAS_BACKEND_CHANGES"
+          echo "Infra changes: $HAS_INFRA_CHANGES"
 
+          ls -l .releaserc.backend.json || echo "Backend config file missing"
+          ls -l .releaserc.frontend.json || echo "Frontend config file missing"
+          
           # Run the correct semantic release config
           if [[ "$HAS_FRONTEND_CHANGES" == true ]]; then
             echo "Running frontend semantic-release"
